apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.appName }}
  description: Aplicação Node.js com PostgreSQL
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
